# Generated by Django 5.2.5 on 2025-08-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.URLField(max_length=2048),
        ),
    ]
